Can view joined tables with big-spenders, mallrats, sassy cats, and c…
SharjeelSIqbal/c0621-code-solutions pull request #99
Opened 2021-08-18 18:56 UTC by SharjeelSIqbal

…ustomers who enjoy that sort of thing 
![Screen Shot 2021-08-18 at 10 49 00 AM (2)](https://user-images.githubusercontent.com/50930123/129956035-ee139f79-0577-40fa-979f-05e6f2e56ba9.png)

2021-08-18 18:57 UTC, SharjeelSIqbal commented
![Screen Shot 2021-08-18 at 10 59 44 AM (2)](https://user-images.githubusercontent.com/50930123/129956126-b9349882-68a3-4d19-a4b3-a3acc69d8c62.png)
![Screen Shot 2021-08-18 at 10 41 08 AM (2)](https://user-images.githubusercontent.com/50930123/129956135-eb6cae3f-c62f-4f64-aece-2ea2b021f0d0.png)
![Screen Shot 2021-08-18 at 11 26 10 AM (2)](https://user-images.githubusercontent.com/50930123/129956142-9d991283-2c44-4007-add9-291b39cca4c3.png)
![Screen Shot 2021-08-18 at 11 54 22 AM (2)](https://user-images.githubusercontent.com/50930123/129956146-f666e9a3-d415-40a9-84bc-29669ae9dd10.png)

2021-08-18 19:00 UTC, thebearingedge requested changes
Just some minor cleanup

2021-08-18 19:00 UTC, thebearingedge commented on sql-join/magic-mallrats.sql
> +"inventory"."inventoryId"
double check the instructions for each SQL file. Only specific columns were requested.

2021-08-20 20:16 UTC, thebearingedge requested changes

2021-08-20 20:16 UTC, thebearingedge commented on sql-join/where-are-they.sql
> +"payments"."customerId",
We don't need any customer info for this one, just full addresses.

![image](https://user-images.githubusercontent.com/7432943/130288957-50ba13a9-d35d-45f9-94e2-fe2425518b1b.png)

2021-08-20 20:26 UTC, thebearingedge requested changes

2021-08-20 20:26 UTC, thebearingedge commented on sql-join/where-are-they.sql
> +join "payments" using ("customerId")
???

2021-08-20 20:26 UTC, thebearingedge commented on sql-join/where-are-they.sql
> +limit 10;
??

2021-08-20 21:21 UTC, thebearingedge approved these changes

2021-08-21 16:47 UTC, merged